#!/bin/bash

##MAKE SFS FROM VCF

##input 1
VCF1=$1
##input 2
VCF2=$2
##outputDIR
outputDIR=$3

cp FreqSpectPlot.R $outputDIR/FreqSpectPlot.R

vcftools \
--gzvcf $VCF1 \
--keep /Users/luke/Documents/MutSpect/data/1000genomes_phase3_sample_IDs_JUST_JPT.txt \
--freq2 \
--out $outputDIR/$(basename "$VCF1" .recode.vcf.gz)

vcftools \
--gzvcf $VCF2 \
--keep /Users/luke/Documents/MutSpect/data/1000genomes_phase3_sample_IDs_JUST_NAG.txt \
--freq2  \
--out $outputDIR/$(basename "$VCF2" .recode.vcf.gz)

Rscript FreqSpectPlot.R \
$outputDIR/$(basename "$VCF1" .recode.vcf).frq \
$outputDIR/$(basename "$VCF2" .recode.vcf).frq \
$outputDIR/SFS_$(basename "$VCF1" .recode.vcf)_$(basename "$VCF2" .recode.vcf)
